const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
export async function api(path,options={}){const token=localStorage.getItem('token');const headers={...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{})};const res=await fetch(API+path,{...options,headers});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||`HTTP ${res.status}`);return data;}
export const login=(email,password)=>api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});
export const register=(fullName,email,password,phone)=>api('/auth/register',{method:'POST',body:JSON.stringify({fullName,email,password,phone})});
export const dashboard=()=>api('/dashboard/summary');
export const sensorHistory=()=>api('/sensors/history');
export const rooms=()=>api('/rooms');
export const createRoom=x=>api('/rooms',{method:'POST',body:JSON.stringify(x)});
export const updateRoom=(id,x)=>api(`/rooms/${id}`,{method:'PATCH',body:JSON.stringify(x)});
export const deleteRoom=id=>api(`/rooms/${id}`,{method:'DELETE'});
export const trays=()=>api('/trays');
export const createTray=x=>api('/trays',{method:'POST',body:JSON.stringify(x)});
export const updateTray=(id,x)=>api(`/trays/${id}`,{method:'PATCH',body:JSON.stringify(x)});
export const deleteTray=id=>api(`/trays/${id}`,{method:'DELETE'});
export const devices=()=>api('/devices');
export const toggleDevice=(id,status)=>api(`/devices/${id}/toggle`,{method:'PATCH',body:JSON.stringify({status})});
export const cameras=()=>api('/cameras');
export const progress=()=>api('/progress');
export const createProgress=x=>api('/progress',{method:'POST',body:JSON.stringify(x)});
export const notifications=()=>api('/notifications');
export const readNotification=id=>api(`/notifications/${id}/read`,{method:'PATCH'});
export const harvests=()=>api('/harvests');
export const createHarvest=x=>api('/harvests',{method:'POST',body:JSON.stringify(x)});
export const packages=()=>api('/packages');
export const users=()=>api('/users');
export const updateUser=(id,x)=>api(`/users/${id}`,{method:'PATCH',body:JSON.stringify(x)});
