CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(180) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN','OPERATOR','CUSTOMER')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rooms (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  location VARCHAR(200),
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rental_packages (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  duration_days INT NOT NULL,
  price NUMERIC(12,2) NOT NULL DEFAULT 0,
  description TEXT
);

CREATE TABLE IF NOT EXISTS trays (
  id SERIAL PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  room_id INT REFERENCES rooms(id) ON DELETE SET NULL,
  package_id INT REFERENCES rental_packages(id) ON DELETE SET NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
  growth_day INT NOT NULL DEFAULT 1,
  growth_total_days INT NOT NULL DEFAULT 30,
  mushroom_variety VARCHAR(120) NOT NULL DEFAULT 'Nấm Bào Ngư Xám',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rentals (
  id SERIAL PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tray_id INT NOT NULL REFERENCES trays(id) ON DELETE CASCADE,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date DATE
);

CREATE TABLE IF NOT EXISTS devices (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  device_type VARCHAR(50) NOT NULL,
  tray_id INT REFERENCES trays(id) ON DELETE SET NULL,
  is_on BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sensor_readings (
  id BIGSERIAL PRIMARY KEY,
  tray_id INT REFERENCES trays(id) ON DELETE CASCADE,
  sensor_type VARCHAR(30) NOT NULL CHECK (sensor_type IN ('TEMPERATURE','HUMIDITY','CO2')),
  value NUMERIC(10,2) NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sensor_time
ON sensor_readings(sensor_type, recorded_at DESC);

CREATE TABLE IF NOT EXISTS alerts (
  id BIGSERIAL PRIMARY KEY,
  tray_id INT REFERENCES trays(id) ON DELETE CASCADE,
  severity VARCHAR(20) NOT NULL DEFAULT 'INFO',
  title VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS harvests (
  id SERIAL PRIMARY KEY,
  tray_id INT REFERENCES trays(id) ON DELETE SET NULL,
  quantity_kg NUMERIC(10,2),
  harvest_date DATE,
  status VARCHAR(30) NOT NULL DEFAULT 'PLANNED',
  notes TEXT
);
